"""Generates a minimal stub ml_engine/pickle/model.pkl so the repo passes a clean-clone smoke test.

This script creates a lightweight model bundle using synthetic data.
The hackathon judge should replace this by running:
    DATA_DIR=ml_engine/data/raw bash run.sh
"""
import pickle
import sys
from pathlib import Path

import numpy as np
import pandas as pd

# Ensure project root is on path
root = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(root))

from ml_engine.forecasting.lgbm_model import LGBMForecaster
from ml_engine.forecasting.prophet_model import ProphetForecaster
from ml_engine.budget.simulator import BudgetSimulator
from ml_engine.model_store.serializer import ModelSerializer


def make_synthetic_df(n_days: int = 90) -> pd.DataFrame:
    rng = np.random.default_rng(42)
    dates = pd.date_range("2024-01-01", periods=n_days, freq="D")
    df = pd.DataFrame({
        "date": dates,
        "channel": "google",
        "campaign_name": "Stub_Campaign",
        "campaign_type": "Search",
        "spend": rng.uniform(50, 300, n_days),
        "revenue": rng.uniform(100, 900, n_days),
        "clicks": rng.integers(20, 200, n_days).astype(float),
        "impressions": rng.integers(500, 5000, n_days).astype(float),
        "conversions": rng.uniform(1, 20, n_days),
        "roas": rng.uniform(1.5, 4.0, n_days),
        "currency": "USD",
        "campaign_id": None,
        "daily_budget": 300.0,
    })
    return df


if __name__ == "__main__":
    print("Generating synthetic training data ...")
    df = make_synthetic_df()

    # Feature engineering
    from ml_engine.features.feature_store import FeatureStore
    fs = FeatureStore(output_dir="/tmp/stub_features")
    features_df = fs.build(df, save=False)

    # Train models
    print("Training stub LightGBM ...")
    lgbm = LGBMForecaster({"n_estimators": 50, "num_leaves": 15})
    lgbm.fit(features_df)

    print("Training stub Prophet ...")
    prophet = ProphetForecaster()
    prophet.fit(df)

    print("Fitting stub BudgetSimulator ...")
    budget_sim = BudgetSimulator()
    budget_sim.fit(df)

    # Save
    out_path = root / "pickle" / "model.pkl"
    ModelSerializer.save(
        path=str(out_path),
        lgbm=lgbm,
        prophet=prophet,
        budget_sim=budget_sim,
        metadata={
            "source": "stub — generated by scripts/generate_stub_model.py",
            "n_train_rows": len(features_df),
            "warning": "Retrain on real data via: DATA_DIR=ml_engine/data/raw bash run.sh",
        },
    )
    print(f"Stub model saved: {out_path}")

